export const CARD_TYPES = [
  {
    id: 'personal',
    label: 'Personal',
    icon: '👤',
    color: '#6c63ff',
    gradient: ['#6c63ff', '#a855f7'],
    description: 'Personal networking card',
    fields: [
      { key: 'name', label: 'Full Name', required: true, placeholder: 'Rahul Sharma' },
      { key: 'phone', label: 'Phone', type: 'phone-pad', placeholder: '+91 98765 43210' },
      { key: 'email', label: 'Email', type: 'email-address', placeholder: 'rahul@gmail.com' },
      { key: 'instagram', label: 'Instagram', placeholder: '@rahulsharma' },
      { key: 'twitter', label: 'X / Twitter', placeholder: '@rahulsharma' },
      { key: 'website', label: 'Website', placeholder: 'https://rahul.dev' },
      { key: 'location', label: 'Location', placeholder: 'Hyderabad, India' },
      { key: 'bio', label: 'Bio', multiline: true, placeholder: 'A short bio about yourself...' },
    ],
  },
  {
    id: 'business',
    label: 'Business',
    icon: '💼',
    color: '#0369a1',
    gradient: ['#0369a1', '#0ea5e9'],
    description: 'Professional business card',
    fields: [
      { key: 'name', label: 'Full Name', required: true, placeholder: 'Rahul Sharma' },
      { key: 'title', label: 'Job Title', placeholder: 'Senior Manager' },
      { key: 'company', label: 'Company', placeholder: 'ABC Pvt Ltd' },
      { key: 'department', label: 'Department', placeholder: 'Sales & Marketing' },
      { key: 'phone', label: 'Work Phone', type: 'phone-pad', placeholder: '+91 98765 43210' },
      { key: 'email', label: 'Work Email', type: 'email-address', placeholder: 'rahul@company.com' },
      { key: 'linkedin', label: 'LinkedIn', placeholder: 'linkedin.com/in/rahul' },
      { key: 'website', label: 'Website', placeholder: 'https://company.com' },
      { key: 'location', label: 'Office Location', placeholder: 'Hyderabad, India' },
    ],
  },
  {
    id: 'ca',
    label: 'CA / Pro',
    icon: '⚖️',
    color: '#15803d',
    gradient: ['#15803d', '#22c55e'],
    description: 'CA & Professional services card',
    fields: [
      { key: 'name', label: 'Full Name', required: true, placeholder: 'CA Rahul Sharma' },
      { key: 'title', label: 'Designation', placeholder: 'Chartered Accountant' },
      { key: 'firm_name', label: 'Firm Name', placeholder: 'Sharma & Associates' },
      { key: 'membership_no', label: 'Membership No.', placeholder: 'ICAI-MH-123456' },
      { key: 'specialization', label: 'Specialization', placeholder: 'Tax, Audit, GST' },
      { key: 'phone', label: 'Phone', type: 'phone-pad', placeholder: '+91 98765 43210' },
      { key: 'email', label: 'Email', type: 'email-address', placeholder: 'ca.rahul@firm.com' },
      { key: 'website', label: 'Website', placeholder: 'https://sharmaassociates.com' },
      { key: 'location', label: 'Office Location', placeholder: 'Hyderabad, India' },
    ],
  },
  {
    id: 'elite',
    label: 'Elite',
    icon: '⭐',
    color: '#b45309',
    gradient: ['#b45309', '#f59e0b'],
    description: 'Premium executive card',
    fields: [
      { key: 'name', label: 'Full Name', required: true, placeholder: 'Rahul Sharma' },
      { key: 'title', label: 'Title', placeholder: 'Founder & CEO' },
      { key: 'company', label: 'Company', placeholder: 'UltraCard Inc.' },
      { key: 'tagline', label: 'Tagline', placeholder: 'Building the future of networking' },
      { key: 'phone', label: 'Phone', type: 'phone-pad', placeholder: '+91 98765 43210' },
      { key: 'whatsapp', label: 'WhatsApp', type: 'phone-pad', placeholder: '+91 98765 43210' },
      { key: 'email', label: 'Email', type: 'email-address', placeholder: 'rahul@ultracard.app' },
      { key: 'linkedin', label: 'LinkedIn', placeholder: 'linkedin.com/in/rahul' },
      { key: 'instagram', label: 'Instagram', placeholder: '@rahulsharma' },
      { key: 'website', label: 'Website', placeholder: 'https://ultracard.app' },
      { key: 'services', label: 'Services', multiline: true, placeholder: 'SaaS, Consulting, Keynote Speaking' },
      { key: 'location', label: 'Location', placeholder: 'Hyderabad, India' },
    ],
  },
];

export const getCardType = (id) =>
  CARD_TYPES.find((t) => t.id === id) || CARD_TYPES[0];
